In [91]:
import torch

In [92]:
# 用arange创建一个行向量x（这个行向量从0开始）
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [93]:
# 可以通过shape属性来访问张量（沿每个轴的长度）的形状
x.shape

torch.Size([12])

In [94]:
# 如果想知道元素的个数，可以检查它的大小
x.numel()

12

In [95]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [96]:
# 幸运的是：我们不必手动计算张量的维度，可以通过-1来调用自动计算维度的功能
Y = x.reshape(3,-1)
Y

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [97]:
# 有时，我们希望创建全0或者全1的张量，比如创建两个通道的形状为(2,3,4)的张量
torch.zeros(2,3,4)


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [98]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [99]:
# 有时，要通过特定的概率随机分布 随机采样来得到张量中的每个元素的值
# 其中，每个元素都是均值为0，标准差为1的正态分布中随机采样
torch.randn(3,4)

tensor([[-1.5932,  0.8796, -1.1735,  2.0519],
        [-1.5602, -1.4522,  1.0612,  0.5275],
        [ 1.2319,  0.9635, -0.1397,  1.4975]])

In [100]:
# 还可以提供嵌套列表，来为所需张量中每个元素赋予确定值
# 这里，最外层的列表对应于轴0
torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

运算符

In [101]:
# 我们可以在同一形状的任意两张张量上调用按元素的操作
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x + y , x - y , x * y , x/y , x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [102]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [103]:
# 我们也可以把张量连接在一起（concatenate）
# 下面的例子分别演示 沿行 和 沿列 拼接两个矩阵
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([
    [2.0,1,4,3],
    [1,2,3,4],
    [4,3,2,1]
])
torch.cat((X,Y),dim=0) , torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [104]:
# 查看两个矩阵是否在对应位置相等
X < Y 

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [105]:
X.sum()

tensor(66.)

In [106]:
Y.sum()

tensor(30.)

广播机制

In [107]:
# 即使两个张量的形状不同，我们仍然可以进行操作
# 首先，适当复制元素来拓展一个或两个数组，以便在转换之后，两个张量具有相同的形状
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [108]:
# 广播机制会将两个矩阵广播为 3*2 的矩阵
# 广播实际上是对原来张量的复制
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

索引和切片

In [109]:
# 和其他的数组一样，张量的数组也可以通过索引访问
# 用-1选择最后一个元素
X[-1] , X[1:3]
# 用切片选择第2,3个元素


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [110]:
# 可以通过指定索引将元素写入矩阵
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [111]:
# 如果我们想给多个元素赋予相同的值，我们只需索引所需的元素
# :代表所有的列
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

转换为其他python对象

In [112]:
# 要将大小为1的张量转换为Python标量，我么你可以调用item函数或Python的内置函数
a = torch.tensor([3.5])
a , a.item() , float(a) , int(a)

(tensor([3.5000]), 3.5, 3.5, 3)