标量

In [13]:
# 标量由只有一个元素的张量组成
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y , x * y , x/y , x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

向量

In [14]:
# 向量可以视为标量组成的列表
# 人们通过一维张量表示向量。一般来说，张量可以具有任意的长度，取决于机器的内存限制
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [15]:
# 可以使用下标来引用向量的任意元素，大量的文献认为列向量是向量的默认方向。
x[3],x[2]

(tensor(3), tensor(2))

长度、维度和形状

In [16]:
# 向量只是一个数字数组，每个向量都有长度。在数学表示法中，如果我们想说一个向量x有n个实值标量组成
# 向量的长度通常成为向量的维度

len(x)

4

请注意，维度这个词在不同的上下文的时候会有不同的含义，这经常会使人感到困惑。为了清除起见，我们明确：向量或轴的2维度被用来表示向量
或轴，即向量或轴的元素数量。然而，张量的维度用来表示张量具有的轴数。在这个意义上，张量的某个轴的维数就是这个轴的长度。

In [17]:
x.shape

torch.Size([4])

矩阵

In [18]:
A = torch.arange(20).reshape(5,-1)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [19]:
# 访问转置矩阵
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [20]:
# 作为方阵的特殊类型，对称矩阵的转置等于自身


张量


In [21]:
# 当我们开始处理图像的时候，张量将变得更加重要，图像以n维数组的形式出现，其中3个轴对应于通道（用于颜色表示）、高度、宽度。
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

张量算法的基本性质

In [26]:
# 我们将两个形状相同的矩阵相加，会在这两个矩阵上执行元素的加法
A = torch.arange(20,dtype=torch.float32).reshape(5,-1)
B = A.clone()
A , A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [27]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

降维

In [28]:
x = torch.arange(4,dtype=torch.float32)
x , x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [29]:
A.shape , A.sum()

(torch.Size([5, 4]), tensor(190.))

In [32]:
# 默认情况下，调用求和函数会沿所有的轴降低张量的维度，使它变为一个标量。
# 我们还可以指定张量沿哪一个轴来通过求和降低维度。
# 以矩阵为例，为了通过求和所有元素行的元素来降维（轴0),可以在调用函数的时候指定axis=0
# 有用输入矩阵沿轴0降维以生成输出向量，因此输入轴0的维数在输出形状中消失

A_sum_axis0 = A.sum(axis=0)
A_sum_axis0 , A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [33]:
# 指定axis = 1将通过汇总所有列的元素降维（轴1）。因此，输入维数在输出形状中消失
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1 , A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [34]:
# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和
A.sum(axis = [0,1])

tensor(190.)

In [35]:
# A.numel() 可以求出张量中一共有多少函数
A.mean() , A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [36]:
A.mean(axis=0) , A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

非降维求和

In [37]:
# 有时，调用函数来计算总和或均值时保持轴数不变会很有用
sum_A = A.sum(axis=1 , keepdim=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [38]:
# 例如，sum_A在对每行进行求和后仍然保持两个轴，我们可以通过广播将A除以sum_A
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [39]:
# 如果我们想沿某个轴计算A元素的累积总和，比如axis=0（按行计算） ，可以调用cumsum函数
# 此函数不会沿着任何轴降低输入张量的维度
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

点积

In [40]:
# 点积就是相同位置按元素相乘
y = torch.ones(4,dtype=torch.float32)
x , y , torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [41]:
# 注意：我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积
torch.sum(x * y)

tensor(6.)

In [ ]:
# 点积在很多场合都有用，将两个向量规范化得到单位长度后，点积表示他们之间夹角的余弦

矩阵-向量积

矩阵-矩阵乘法

In [42]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [43]:
B = torch.ones(4,3)
torch.mm(A , B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

范数

In [45]:
# 非正式的说，向量的范数就是这个向量有多大。
# 这里考虑的大小概念不涉及维度，而是分量的大小
# L2范数是向量元素和的平方根

u = torch.tensor([3.0 , -4.0])
torch.norm(u)

tensor(5.)

In [48]:
# 为了计算L1范数，我们将绝对值函数和按元素求和组合起来
torch.abs(u).sum(axis=0)

tensor(7.)